version: '3'
services:
  backend-1:
    build: .
    ports:
      - "5000"

  backend-2:
    build: .
    ports:
      - "5000"

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"

